[package]
name = "ratu-aurion-index"
version = "0.1.0"
edition = "2021"

[dependencies]
ratu-aurion-primitives = { path = "../ratu-aurion-primitives" }
ratu-aurion-storage = { path = "../ratu-aurion-storage" }
blake3 = { version = "1.5", default-features = false, features = ["pure"] }

[lints]
workspace = true
